let
    // 建立表格
    surce = #table(
        {"id", "name", "mail"},  // 欄位名稱
        
        // 資料內容，也適用{}包起來
        {
            {1, "Bill", "bill@gmail.com"},  
            {2, "Tom", "tom@gmail.com"},
            {3, "Mark", "Mark@gmail.com"}
        }
    )
in
    surce  // 回傳變數





let
    計算價格 = #Table(
        {"單價", "數量"},

        {
            {2,1},{2,2}{2,3},{2,4}{2,5}
        }

    )
in
    來源
